### PR TITLE
Replace vtk with PolygonalMesh from simtk

### PR DESCRIPTION
**Pull request by aymanhab**
This branch uses SimTK parsers to avoid pulling in the massive vtk library but has some deficiencies due to lack of reading mesh normals in vtp files and to the missing torus analytical shape

### CODE REVIEW

**Comment by aymanhab** [comment]
This addresses issue #10 and will fix it when the deficiencies above are addresssed

**Comment by aymanhab** [comment]
@AlbertoCasasOrtiz For your review. Would be good to get this in to be ready for the normals and textures from simbody PR

**Review by AlbertoCasasOrtiz — APPROVED** [review]
Just tested by converting a few models to GLTF and it is working correctly. LGTM!

**Comment by aymanhab** [comment]
Thanks much @AlbertoCasasOrtiz 👍

**Pull request merged**
